name: AWS Credentials Test
on: [push]

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::339712877151:role/GitHubAction-AssumeRoleWithAction
          aws-region: eu-central-1
      
      - name: Test AWS CLI
        run: aws sts get-caller-identity
